/*
Company: OptimaJet
Site: https://workflowngine.io (https://workflowenginenet.com)
Project: WorkflowEngineJava Provider for MSSQL
Version: 2.0
File: DropPersistenceObjects.sql
*/

DROP TABLE WORKFLOWINBOX;
DROP TABLE WORKFLOWPROCESSINSTANCE;
DROP TABLE WORKFLOWPROCESSSCHEME;
DROP TABLE WORKFLOWPROCESSTIMER;
DROP TABLE WORKFLOWPROCESSTRANSITIONH;
DROP TABLE WORKFLOWPROCESSINSTANCEP;
DROP TABLE WORKFLOWSCHEME;
DROP TABLE WORKFLOWPROCESSINSTANCES;
DROP TABLE WORKFLOWGLOBALPARAMETER;

COMMIT;